name: Run RFQ Wizard Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show file structure
        run: ls -R .

      - name: Run tests with pytest
        run: pytest test_rfq_wizard.py --maxfail=5 --disable-warnings -v
